development:
  adapter: sqlserver
  database: MyBlog
  dataserver: 'WayTooGonzo'
  username: sa
  password: '78799141'
  pool: 5
  timeout: 5000

test:
  adapter: sqlserver
  database: MyBlog
  dataserver: 'WayTooGonzo'
  username: sa
  password: '78799141'
  pool: 5
  timeout: 5000

production:
  adapter: sqlserver
  database: MyBlog
  dataserver: 'WayTooGonzo'
  username: sa
  password: '78799141'
  pool: 5
  timeout: 5000
